/* Create users table */
CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL, 
    email text NOT NULL, 
    password text NOT NULL
);

/* Create tasks table */
CREATE TABLE IF NOT EXISTS tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    responsable text NOT NULL, 
    description text NOT NULL,
    userId INTEGER PREFERENCES users(id)
);

/* Insert a task */
INSERT INTO tasks(responsable, description)
    VALUES('Sebastian', 'Cocinar', 1);